/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Controller.Service.GiaoVienService;
import Controller.Service.LoginService;
import Controller.ServiceImpl.GiaoVienServiceImpl;
import Model.GiaoVien;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatArcIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import org.codehaus.griffon.runtime.lookandfeel.synthetica.SyntheticaLookAndFeelModule;

/**
 *
 * @author leope
 */
public class LoginFrame extends javax.swing.JFrame implements ActionListener, KeyListener, MouseListener {

    
    private GiaoVienService giaoVienService;
    /**
     * Creates new form LoginForm
     * 
     * 
     */
    public LoginFrame() {      
            try {
            FlatIntelliJLaf.setup();
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatIntelliJLaf");
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();      
        giaoVienService = new GiaoVienServiceImpl(); // injection       

    }

    public void modifyComponent() {
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLogin = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        passWordLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        passWordField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        copyRight_label = new javax.swing.JLabel();
        showPasswordBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lý đào tạo THCS");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new ImageIcon("src\\View\\icons\\icons8_school_96px.png").getImage());
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        addKeyListener(this);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainLogin.setBackground(new java.awt.Color(255, 255, 255));
        mainLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainLogin.addKeyListener(this);

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(0, 204, 204));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_password_40px.png"))); // NOI18N
        loginLabel.setText("Đăng nhập");

        userNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(0, 204, 204));
        userNameLabel.setText("Tên đăng nhập:");

        userNameTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userNameTextField.setBorder(null);
        userNameTextField.setOpaque(true);
        userNameTextField.addActionListener(this);

        jSeparator1.setForeground(new java.awt.Color(0, 204, 204));

        passWordLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passWordLabel.setForeground(new java.awt.Color(0, 204, 204));
        passWordLabel.setText("Mật khẩu:");
        passWordLabel.setMaximumSize(new java.awt.Dimension(106, 20));
        passWordLabel.setMinimumSize(new java.awt.Dimension(106, 20));
        passWordLabel.setPreferredSize(new java.awt.Dimension(106, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 204, 204));

        passWordField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passWordField.setBorder(null);

        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(0, 204, 204));
        LoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_enter_48px_1.png"))); // NOI18N
        LoginButton.setText("Đăng nhập");
        LoginButton.setToolTipText("Đăng nhập");
        LoginButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.addMouseListener(this);

        copyRight_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        copyRight_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyRight_label.setText("© Nhóm 3 - KTPMUD -129211");
        copyRight_label.setToolTipText("");

        showPasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_eye_24px.png"))); // NOI18N
        showPasswordBtn.setToolTipText("Hiển thị mật khẩu");
        showPasswordBtn.setBorder(null);
        showPasswordBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_invisible_24px.png"))); // NOI18N
        showPasswordBtn.addMouseListener(this);

        javax.swing.GroupLayout mainLoginLayout = new javax.swing.GroupLayout(mainLogin);
        mainLogin.setLayout(mainLoginLayout);
        mainLoginLayout.setHorizontalGroup(
            mainLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLoginLayout.createSequentialGroup()
                .addGroup(mainLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLoginLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(mainLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passWordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addGroup(mainLoginLayout.createSequentialGroup()
                                .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(mainLoginLayout.createSequentialGroup()
                                .addComponent(passWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showPasswordBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(mainLoginLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(copyRight_label, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(mainLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLoginLayout.createSequentialGroup()
                        .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLoginLayout.createSequentialGroup()
                        .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        mainLoginLayout.setVerticalGroup(
            mainLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLoginLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(mainLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainLoginLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(mainLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLoginLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(passWordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainLoginLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(mainLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passWordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showPasswordBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(copyRight_label)
                .addGap(15, 15, 15))
        );

        getContentPane().add(mainLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 0, 350, 420));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/image/anh_truong_hoc.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 420));

        pack();
        setLocationRelativeTo(null);
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == userNameTextField) {
            LoginFrame.this.userNameTextFieldActionPerformed(evt);
        }
    }

    public void keyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getSource() == LoginFrame.this) {
            LoginFrame.this.formKeyPressed(evt);
        }
        else if (evt.getSource() == mainLogin) {
            LoginFrame.this.mainLoginKeyPressed(evt);
        }
    }

    public void keyReleased(java.awt.event.KeyEvent evt) {
    }

    public void keyTyped(java.awt.event.KeyEvent evt) {
    }

    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == LoginButton) {
            LoginFrame.this.LoginButtonMouseClicked(evt);
        }
    }

    public void mouseEntered(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == showPasswordBtn) {
            LoginFrame.this.showPasswordBtnMouseEntered(evt);
        }
    }

    public void mouseExited(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == showPasswordBtn) {
            LoginFrame.this.showPasswordBtnMouseExited(evt);
        }
    }

    public void mousePressed(java.awt.event.MouseEvent evt) {
    }

    public void mouseReleased(java.awt.event.MouseEvent evt) {
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextFieldActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            new HostFrame().setVisible(true);       
        }
    }//GEN-LAST:event_formKeyPressed

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        // TODO add your handling code here
      boolean loginCheck = LoginService.login(userNameTextField.getText(), String.valueOf(passWordField.getPassword()));
      if(loginCheck)
          {
         GiaoVien giaoVien = giaoVienService.findByTenDangNhap(userNameTextField.getText()).get();
        String tenGiaoVien = giaoVien.getTenGiaoVien();
        new JOptionPane().showMessageDialog(null, "Bạn đã đăng nhập thành công !  Xin chào "+tenGiaoVien );
        HostFrame hostFrame = new HostFrame();
        hostFrame.getLoginInfo(userNameTextField.getText(), giaoVien.getChucVu());
        this.dispose();
        hostFrame.setVisible(true);
        }
      else
          new JOptionPane().showMessageDialog(null, "Tài khoản hoặc mật khẩu không đúng ! Vui lòng kiểm tra lại.");
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void mainLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainLoginKeyPressed
        // TODO add your handling code here:
//        if(evt.getKeyCode() ==KeyEvent.VK_ENTER)
//            HostFrame hostFrame =new HostFrame(); 

    }//GEN-LAST:event_mainLoginKeyPressed

    private void showPasswordBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPasswordBtnMouseExited
        passWordField.setEchoChar('\u2022');
    }//GEN-LAST:event_showPasswordBtnMouseExited

    private void showPasswordBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPasswordBtnMouseEntered
       if(passWordField.getPassword().length!=0)
           {
            passWordField.setEchoChar((char)0); 
           }
    }//GEN-LAST:event_showPasswordBtnMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>
        /* Create and display the form */
       try {            
             FlatIntelliJLaf.setup();
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatIntelliJLaf");             
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel copyRight_label;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel mainLogin;
    private javax.swing.JPasswordField passWordField;
    private javax.swing.JLabel passWordLabel;
    private javax.swing.JButton showPasswordBtn;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
